In [12]:
with open('sol_heating_Pseudotsuga_menziesii.dat', 'r') as f:
    run_time = f.readlines()[-2]

In [18]:
run_time.split()

['175.92592592592592',
 '773.15',
 '9.46536726723e-16',
 '-1.70681106073e-115',
 '0.222755541318',
 '0.000426121553641',
 '0.00251104263559',
 '0.0194998850162',
 '0.0185528526882',
 '0.00221223449948',
 '0.16535058201',
 '0.0343089848408',
 '0.0194599759591',
 '0.0013672215921',
 '1.6959204387',
 '0.157852857537',
 '0.698753064787',
 '0.00607087328838',
 '1.65402034665',
 '0.086981261142',
 '0.395976932237',
 '0.0194253821212',
 '0.0310554887797',
 '3.09015191709',
 '2.45712273926',
 '4.22098240008e-08',
 '0.718084775318',
 '0.0177213189711',
 '1.11527948458e-104',
 '4.21907774342e-08',
 '0.000296395213434',
 '3.82580444744e-185',
 '1.6004227038e-108',
 '8.00144181897e-144',
 '0.00833481710508',
 '4.90584874037e-07',
 '0.000839516679894',
 '0.000445997116355',
 '0.968137799675',
 '3.27904588737e-12',
 '0.222465263062',
 '5.7540384356e-09',
 '3.18184898428e-07',
 '1.87184005385e-12',
 '0.181153621595',
 '1.68829468294',
 '1.551158483e-16',
 '2.83054872014',
 '2.11716512309e-08',
 '-1.9

In [22]:
from scipy.integrate import odeint
import numpy as np

In [23]:
def df(f,t):
    return f-2

In [45]:
f0 = 1
t0 = 0
t_max = 5
nout = 100
ts = np.linspace(t0,t_max,nout)

In [25]:
ts

array([ 0.        ,  0.05050505,  0.1010101 ,  0.15151515,  0.2020202 ,
        0.25252525,  0.3030303 ,  0.35353535,  0.4040404 ,  0.45454545,
        0.50505051,  0.55555556,  0.60606061,  0.65656566,  0.70707071,
        0.75757576,  0.80808081,  0.85858586,  0.90909091,  0.95959596,
        1.01010101,  1.06060606,  1.11111111,  1.16161616,  1.21212121,
        1.26262626,  1.31313131,  1.36363636,  1.41414141,  1.46464646,
        1.51515152,  1.56565657,  1.61616162,  1.66666667,  1.71717172,
        1.76767677,  1.81818182,  1.86868687,  1.91919192,  1.96969697,
        2.02020202,  2.07070707,  2.12121212,  2.17171717,  2.22222222,
        2.27272727,  2.32323232,  2.37373737,  2.42424242,  2.47474747,
        2.52525253,  2.57575758,  2.62626263,  2.67676768,  2.72727273,
        2.77777778,  2.82828283,  2.87878788,  2.92929293,  2.97979798,
        3.03030303,  3.08080808,  3.13131313,  3.18181818,  3.23232323,
        3.28282828,  3.33333333,  3.38383838,  3.43434343,  3.48

In [31]:
f = odeint(df, f0, [ts[0], ts[1]])

In [32]:
f

array([[ 1.        ],
       [ 0.94819784]])

In [33]:
len(ts)

100

In [48]:
i = 0
f0 = 1
while i < (len(ts)-1):
    f = odeint(df, f0, [ts[i], ts[i+1]])
    if f[1][0] < 0:
        f[1][0] = 0
    f0 = f[1][0]
    print(f[1][0])
    i += 1

0.948197836505
0.89371220796
0.836404104916
0.77612731691
0.71272805946
0.646044581734
0.575906753887
0.502135633039
0.424543005513
0.342930910682
0.257091131151
0.16680466359
0.0718411599996
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [39]:
ts[98], ts[99]

(4.9494949494949498, 5.0)

In [41]:
f

array([[ 0.        ],
       [-0.10360435]])